name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^2.0.0 
  google_fonts: ^6.2.0
  sizer: ^2.0.15
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  gettext: ^1.2.0
  get: ^4.6.6
  firebase_auth: ^4.20.0
  flutter_credit_card: ^4.0.1
  firebase_service: ^0.0.1+1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  assets:
    - assets/images/
  uses-material-design: true
