// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pvW8cYzazyqeWS9TDqXrBWBSX9h9VL4',
    appId: '1:205512445967:web:2488e5c6bfd45fa7e7d37a',
    messagingSenderId: '205512445967',
    projectId: 'wapdeneme-8e545',
    authDomain: 'wapdeneme-8e545.firebaseapp.com',
    storageBucket: 'wapdeneme-8e545.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxaZP20IpfbPONY3iYTyJNz5eH85F5ekQ',
    appId: '1:205512445967:android:fb16667f30ebcb84e7d37a',
    messagingSenderId: '205512445967',
    projectId: 'wapdeneme-8e545',
    storageBucket: 'wapdeneme-8e545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7H4jq3qhgHJwUtUU4sWIlTpatVkJgus',
    appId: '1:205512445967:ios:1802d244f5e9f9e9e7d37a',
    messagingSenderId: '205512445967',
    projectId: 'wapdeneme-8e545',
    storageBucket: 'wapdeneme-8e545.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7H4jq3qhgHJwUtUU4sWIlTpatVkJgus',
    appId: '1:205512445967:ios:1802d244f5e9f9e9e7d37a',
    messagingSenderId: '205512445967',
    projectId: 'wapdeneme-8e545',
    storageBucket: 'wapdeneme-8e545.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0pvW8cYzazyqeWS9TDqXrBWBSX9h9VL4',
    appId: '1:205512445967:web:e879c235ffa71bbee7d37a',
    messagingSenderId: '205512445967',
    projectId: 'wapdeneme-8e545',
    authDomain: 'wapdeneme-8e545.firebaseapp.com',
    storageBucket: 'wapdeneme-8e545.appspot.com',
  );

}